jobs:
- job: BuildWindowsWithSonarCloud
  displayName: Build for Windows\MSBuild With SonarCloud
  pool:
    vmImage: 'windows-latest'
  variables:
    BUILD_WRAPPER_DOWNLOAD_URL: https://sonarcloud.io/static/cpp/build-wrapper-win-x86.zip
  steps:
  - checkout: self
    fetchDepth: 0 # Need blame information for SonarCloud
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud' # Name of the SonarCloud service connection you created
      organization: 'sonarsource-cfamily-examples'
      scannerMode: 'MSBuild'
      configMode: 'manual'
      projectKey: 'sonarsource-cfamily-examples_windows-msbuild-dotnet-cpp-azure-sc'
      extraProperties: |
        sonar.cfamily.compile-commands=$(Pipeline.Workspace)\build_wrapper_output_directory\compile_commands.json
  - pwsh: |
      curl --create-dirs -sSLo $HOME\.sonar\build-wrapper-win-x86.zip ${{variables.BUILD_WRAPPER_DOWNLOAD_URL}}
      Expand-Archive $HOME\.sonar\build-wrapper-win-x86.zip -DestinationPath $HOME\.sonar\ -Force
    displayName: Download and install build wrapper
  - pwsh: |
      $msbuild = vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | select-object -first 1
      & $msbuild windows-msbuild-dotnet-cpp.sln /t:restore
      & "$HOME\.sonar\build-wrapper-win-x86\build-wrapper-win-x86-64.exe" --out-dir $(Pipeline.Workspace)\build_wrapper_output_directory $msbuild windows-msbuild-dotnet-cpp.sln /t:rebuild /nodeReuse:false
    workingDirectory: .
    displayName: Build in build-wrapper
  - task: SonarCloudAnalyze@1
